// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Calle;

import Calle.Vehículo;

/************************************************************/
/**
 * 
 */
public class Bicicleta extends Vehículo {

	/**
	 * 
	 */
	private int tamañoMarco;

	/**
	 * @param color
	 * @param velocidad
	 * @param tamañoMarco
	 */
	public Bicicleta(String color, int velocidad, int tamañoMarco) {
		super(color, velocidad);
		this.tamañoMarco = tamañoMarco;
	}

	/**
	 * @return the tamañoMarco
	 */
	public int getTamañoMarco() {
		return tamañoMarco;
	}

	/**
	 * @param tamañoMarco the tamañoMarco to set
	 */
	public void setTamañoMarco(int tamañoMarco) {
		this.tamañoMarco = tamañoMarco;
	}

	

};
