// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Calle;

/**
 * 
 */
public enum ConstantesTipoCarro {
	/**
	 * 
	 */
	SEDAN,
	/**
	 * 
	 */
	PICKUP,
	/**
	 * 
	 */
	HASHBACK,
	/**
	 * 
	 */
	DEPORTIVO;
};
