// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Calle;

/************************************************************/
/**
 * 
 */
public enum ConstantesTipoMotocicleta {
	/**
	 * 
	 */
	STANDARD,
	/**
	 * 
	 */
	CRUCERO,
	/**
	 * 
	 */
	DEPORTIVA,
	/**
	 * 
	 */
	SCOOTER;
};
