// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Calle;

import Calle.Riteve;
import Calle.VehículoAutomotor;
import Calle.ConstantesTipoMotocicleta;

/************************************************************/
/**
 * 
 */
public class Motocicleta extends VehículoAutomotor implements Riteve {
	/**
	 * 
	 */
	private ConstantesTipoMotocicleta estiloMoto;
	
	

	/**
	 * @param color
	 * @param velocidad
	 * @param númeroMotor
	 */
	public Motocicleta(String color, int velocidad, String númeroMotor) {
		super(color, velocidad, númeroMotor);
		// TODO Auto-generated constructor stub
	}

	/**
	 * @param color
	 * @param velocidad
	 */
	public Motocicleta(String color, int velocidad) {
		super(color, velocidad);
		// TODO Auto-generated constructor stub
	}

	/**
	 * @param color
	 * @param velocidad
	 * @param estiloMoto
	 */
	public Motocicleta(String color, int velocidad, ConstantesTipoMotocicleta estiloMoto) {
		super(color, velocidad);
		this.estiloMoto = estiloMoto;
	}

	public ConstantesTipoMotocicleta getEstiloMoto() {
		return estiloMoto;
	}

	public void setEstiloMoto(ConstantesTipoMotocicleta estiloMoto) {
		this.estiloMoto = estiloMoto;
	}

	/**
	 * 
	 * @return
	 */
	public int sacarCitaRiteve() {
		return 1;
	}

	/**
	 * 
	 * @param idCita
	 * @return
	 */
	@Override
	public boolean cancelarCitaRiteve(int idCita) {
		// TODO Auto-generated method stub
		return false;
	}

};