// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Calle;

import Calle.Vehículo;

/************************************************************/
/**
 * 
 */
public abstract class VehículoAutomotor extends Vehículo {
	/**
	 * 
	 */
	private String númeroMotor;

	
	
	/**
	 * 
	 */
	public VehículoAutomotor() {
	}



	/**
	 * @param color
	 * @param velocidad
	 */
	public VehículoAutomotor(String color, int velocidad) {
		super(color, velocidad);
		// TODO Auto-generated constructor stub
	}

	

	/**
	 * @param color
	 * @param velocidad
	 * @param númeroMotor
	 */
	public VehículoAutomotor(String color, int velocidad, String númeroMotor) {
		super(color, velocidad);
		this.númeroMotor = númeroMotor;
	}



	/**
	 * 
	 * @return 
	 */
	public boolean apagar() {
		return true;
	}



	/**
	 * 
	 * @return 
	 */
	public boolean encender() {
		return true;
	}



	public String getNúmeroMotor() {
		return númeroMotor;
	}

	public void setNúmeroMotor(String númeroMotor) {
		this.númeroMotor = númeroMotor;
	}
};
