// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Calle;

import Calle.VehículoAutomotor;

/************************************************************/
/**
 * 
 */
public class VehículoAgrícola extends VehículoAutomotor {
	/**
	 * 
	 */
	public String permisoMag;

	/**
	 * @param color
	 * @param velocidad
	 * @param númeroMotor
	 */
	public VehículoAgrícola(String color, int velocidad, String númeroMotor) {
		super(color, velocidad, númeroMotor);
		// TODO Auto-generated constructor stub
	}

	
	/**
	 * @param color
	 * @param velocidad
	 * @param númeroMotor
	 * @param permisoMag
	 */
	public VehículoAgrícola(String color, int velocidad,  String númeroMotor,String permisoMag) {
		super(color, velocidad);
		this.permisoMag = permisoMag;
	}


	public String getPermisoMag() {
		return permisoMag;
	}

	public void setPermisoMag(String permisoMag) {
		this.permisoMag = permisoMag;
	}

	
};
