// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Calle;

/************************************************************/
/**
 * 
 */
public class Vía {

	/**
	 * 
	 */
	private int finalVía;

	public int getFinalVía() {
		return finalVía;
	}

	public void setFinalVía(int finalVía) {
		this.finalVía = finalVía;
	}

	public int getInicioVía() {
		return inicioVía;
	}

	public void setInicioVía(int inicioVía) {
		this.inicioVía = inicioVía;
	}

	/**
	 * 
	 */
	private int inicioVía;

};
