// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Calle.Calle;

import Calle.Calle.Vehículo;

/************************************************************/
/**
 * 
 */
public class Bicicleta extends Vehículo {
	/**
	 * 
	 */
	private int tamañoMarco;
};
