// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Calle.Calle;

import Calle.Calle.Riteve;
import Calle.Calle.VehículoAutomotor;

/************************************************************/
/**
 * 
 */
public class Motocicleta extends VehículoAutomotor implements Riteve {
	/**
	 * 
	 */
	private String estiloMoto;

	/**
	 * 
	 * @return 
	 */
	public int sacarCitaRiteve() {
		return 0;
	}

	/**
	 * 
	 * @param  
	 * @return 
	 */

	public boolean cancelarCitaRiteve(int idCita) {
		// TODO Auto-generated method stub
		return false;
	}};
