// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Calle.Calle;

/************************************************************/
/**
 * 
 */
public interface Riteve {
	/**
	 * 
	 * @return 
	 */
	public int sacarCitaRiteve();

	/**
	 * 
	 * @param idCita 
	 * @return 
	 */
	public boolean cancelarCitaRiteve(int idCita);
};
