// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Calle.Calle;

/************************************************************/
/**
 * 
 */
public class Vehículo {
	/**
	 * 
	 */
	private String color;
	/**
	 * 
	 */
	private int velocidad;

	
	public void setVelocidad(int nuevaVelocidad) {
		this.velocidad=nuevaVelocidad;
	}
	
	public int getVelocidad() {
		return this.velocidad;
	}
	/**
	 * 
	 * @return 
	 */
	public boolean mover() {
		return false;
	}

	/**
	 * 
	 * @return 
	 */
	public boolean detener() {
		return false;
	}
};
