// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Calle.Calle;

import Calle.Calle.VehículoAutomotor;

/************************************************************/
/**
 * 
 */
public class VehículoAgrícola extends VehículoAutomotor {
	/**
	 * 
	 */
	public String permisoMag;
};
