// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Calle.Calle;

import Calle.Calle.Vehículo;

/************************************************************/
/**
 * 
 */
public abstract class VehículoAutomotor extends Vehículo {
	/**
	 * 
	 */
	private String númeroMotor;

	/**
	 * 
	 * @return 
	 */
	public boolean apagar() {
		return false;
	}

	/**
	 * 
	 * @return 
	 */
	public boolean encender() {
		return false;
	}
};
